"""added last_time on notifications table

Revision ID: 00e9a5723531
Revises: ee65c89da2fb
Create Date: 2020-09-05 22:05:24.805594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e9a5723531'
down_revision = 'ee65c89da2fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('last_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'last_time')
    # ### end Alembic commands ###
