"""Initail migration

Revision ID: d3bef07dbca8
Revises: 
Create Date: 2020-09-23 15:35:03.602582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3bef07dbca8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'msg_read')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('msg_read', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
