"""Initial migration.

Revision ID: e5f8a2d7359a
Revises: 
Create Date: 2020-09-23 16:36:42.371765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f8a2d7359a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'msg_read')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('msg_read', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
