"""added last_author on notifications table

Revision ID: ee65c89da2fb
Revises: 878864d235a0
Create Date: 2020-09-05 17:16:46.767962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee65c89da2fb'
down_revision = '878864d235a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('last_author', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'last_author')
    # ### end Alembic commands ###
